os:
  - linux

sudo: false

dist: bionic

git:
  depth: 5

script:
  - make test

# Notifications are encrypted to cleanflight/unified-targets to avoid spam from forks
# Command: `travis encrypt "<secret>" -r cleanflight/unified-targets --com`

#notifications:
#  slack:
#    rooms:
#      - secure: 
#  webhooks:
#    urls:
#      - secure: 
#    on_success: always  # options: [always|never|change] default: always
#    on_failure: always  # options: [always|never|change] default: always
#    on_start: always     # options: [always|never|change] default: always
